// Generated by CoffeeScript 1.7.1
(function() {
  var parser, should, _;

  parser = require("../lib/index");

  should = require("should");

  _ = require("underscore");

  describe("parser test", function() {
    return it("should parse ok", function(done) {
      var e, url;
      try {
        url = "http://stackoverflow.com/questions/244777/can-i-comment-a-json-file";
        return parser.parse(url, function(err, article) {
          should.not.exist(err);
          article.title.should.be.a.String.and.be.exactly("Can I comment a JSON file?");
          article.tags.should.matchEach(function(it) {
            return it.should.be.a.String.and.not.be.empty;
          });
          article.answers.should.be.an.Array;
          article.answers.should.matchEach(function(it) {
            return it.content.should.be.a.String.and.not.be.empty;
          });
          return done();
        });
      } catch (_error) {
        e = _error;
        return console.dir(e);
      }
    });
  });

}).call(this);

//# sourceMappingURL=parse.test.map
