// Generated by CoffeeScript 1.7.1
(function() {
  var cheerio, util, _parse;

  util = require("./util");

  cheerio = require("cheerio");

  exports.parse = function(url, cb) {
    if (url) {
      if (util.isStackoverflowQuestion(url)) {
        return _parse(url, cb);
      } else {
        return cb(new Error("url " + url + " isn't a stackoverflow question page."));
      }
    } else {
      return cb(new Error("must supply a url"));
    }
  };

  _parse = function(url, cb) {
    return util.download(url, function(err, content) {
      var $, answers, answersArr, article, question, tagElements, tags, title;
      if (err) {
        return cb(err);
      }
      $ = cheerio.load(content);
      title = $("#question-header .question-hyperlink").text().trim();
      question = $(".question .post-text").html().trim();
      tags = [];
      tagElements = $(".post-taglist .post-tag");
      tagElements.each(function(i, el) {
        return tags.push($(el).text().trim());
      });
      answersArr = [];
      answers = $(".answercell");
      answers.each(function() {
        var answerDetail, node;
        node = $(this);
        answerDetail = node.find(".post-text");
        util.trimAttrs(answerDetail);
        return answersArr.push({
          content: answerDetail.html().trim()
        });
      });
      article = {
        title: title,
        question: question,
        tags: tags,
        answers: answersArr
      };
      return cb(null, article);
    });
  };

}).call(this);

//# sourceMappingURL=index.map
